/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemaventas.views;

import java.awt.Color;

/**
 *
 * @author Kaniory
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpMain = new javax.swing.JDesktopPane();
        panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btProducto = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        btDetalle = new javax.swing.JButton();
        btVentas = new javax.swing.JButton();
        jpSalir = new javax.swing.JPanel();
        jlSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpMain.setBackground(new java.awt.Color(255, 255, 255));
        jdpMain.setPreferredSize(new java.awt.Dimension(800, 700));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btProducto.setBackground(new java.awt.Color(255, 255, 255));
        btProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btProducto.setText("Producto");
        btProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, -1));

        btCliente.setBackground(new java.awt.Color(255, 255, 255));
        btCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCliente.setText("Cliente");
        btCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 130, 180, -1));

        btDetalle.setBackground(new java.awt.Color(255, 255, 255));
        btDetalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDetalle.setText("Detalle de ventas");
        btDetalle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(btDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 170, 180, -1));

        btVentas.setBackground(new java.awt.Color(255, 255, 255));
        btVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVentas.setText("Ventas");
        btVentas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 210, 180, -1));

        jpSalir.setBackground(new java.awt.Color(0, 51, 153));
        jpSalir.setPreferredSize(new java.awt.Dimension(34, 34));

        jlSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("x");
        jlSalir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlSalir.setPreferredSize(new java.awt.Dimension(34, 34));
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlSalirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpSalirLayout = new javax.swing.GroupLayout(jpSalir);
        jpSalir.setLayout(jpSalirLayout);
        jpSalirLayout.setHorizontalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );
        jpSalirLayout.setVerticalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jpSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 36, 20));

        panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 173, 700));

        jdpMain.setLayer(panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpMainLayout = new javax.swing.GroupLayout(jdpMain);
        jdpMain.setLayout(jdpMainLayout);
        jdpMainLayout.setHorizontalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jdpMainLayout.setVerticalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductoActionPerformed
        // TODO add your handling code here:
        panel.setVisible(false);
        ProductosView p = new ProductosView();
        p.setVisible(true);
        jdpMain.add(p);
        jdpMain.moveToFront(p);
    }//GEN-LAST:event_btProductoActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        // TODO add your handling code here:
        panel.setVisible(false);
        ClientesView c = new ClientesView();
        c.setVisible(true);
        jdpMain.add(c);
        jdpMain.moveToFront(c);
    }//GEN-LAST:event_btClienteActionPerformed

    private void btVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVentasActionPerformed
        // TODO add your handling code here:
        panel.setVisible(false);
        VentasView vvw = new VentasView();
        vvw.setVisible(true);
        jdpMain.add(vvw);
        jdpMain.moveToFront(vvw);
    }//GEN-LAST:event_btVentasActionPerformed

    private void btDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetalleActionPerformed
        
//        panel.setVisible(false);
        DetalleVentaView detaVentas = new DetalleVentaView();
        detaVentas.setVisible(true);
        jdpMain.add(detaVentas);
        jdpMain.moveToFront(detaVentas);
    }//GEN-LAST:event_btDetalleActionPerformed

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMousePressed
        
    }//GEN-LAST:event_jlSalirMousePressed

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited
        
        jpSalir.setBackground(new Color(0, 51, 153));
        jlSalir.setForeground(Color.white);
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered
        
        jpSalir.setBackground(Color.red);
        jlSalir.setForeground(Color.black);
    }//GEN-LAST:event_jlSalirMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void mostrarMenu(){
        panel.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btDetalle;
    private javax.swing.JButton btProducto;
    private javax.swing.JButton btVentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpMain;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JPanel jpSalir;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
