/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistemaventas.views;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import sistemaventas.accesoDatos.ProductoData;
import sistemaventas.entidades.Producto;

/**
 *
 * @author Kaniory
 */
public class ProductosView extends javax.swing.JInternalFrame {

    ProductoData pd = new ProductoData();

    /**
     * Creates new form ProductosView
     */
    public ProductosView() {
        initComponents();
        setearIcono(jLabel6, "src/Imagenes/logo fravemax azul.png");
        modelo();
        listarProductos();
        borrado();
    }

    private DefaultTableModel tabla = new DefaultTableModel() {

        public boolean isCellEditable(int f, int c) {

            return false;
        }
    };

    private void modelo() {
        tabla.addColumn("Codigo");
        tabla.addColumn("Producto");
        tabla.addColumn("Descripcion");
        tabla.addColumn("Precio");
        tabla.addColumn("Stock");
        tabla.addColumn("Estado");
        jtable.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpSalir = new javax.swing.JPanel();
        jlSalir = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jrbEstado = new javax.swing.JRadioButton();
        btBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtDesc = new javax.swing.JTextField();
        lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jtStock = new javax.swing.JTextField();
        btAgregar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        btLimpiar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(690, 120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 0, 120, 120));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUCTOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 32, -1, -1));

        jpSalir.setBackground(new java.awt.Color(0, 51, 153));

        jlSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSalir.setText("x");
        jlSalir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlSalirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpSalirLayout = new javax.swing.GroupLayout(jpSalir);
        jpSalir.setLayout(jpSalirLayout);
        jpSalirLayout.setHorizontalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpSalirLayout.setVerticalGroup(
            jpSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSalirLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jpSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo");

        jtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtIdKeyTyped(evt);
            }
        });

        jLabel4.setText("Nombre");

        jtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreKeyTyped(evt);
            }
        });

        jLabel5.setText("Descripcion");

        jtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDescKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDescKeyTyped(evt);
            }
        });

        lbl.setText("Precio");

        jLabel7.setText("Stock");

        jLabel2.setText("Estado");

        jtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPrecioKeyTyped(evt);
            }
        });

        jtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtStockKeyTyped(evt);
            }
        });

        btAgregar.setText("Agregar / Modificar");
        btAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarActionPerformed(evt);
            }
        });

        btBorrar.setText("Dar de baja");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        btLimpiar.setText("Limpiar campos");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(33, 33, 33)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbEstado)
                            .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(lbl)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btBuscar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btLimpiar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btAgregar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btBorrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jrbEstado))
                        .addGap(18, 18, 18)
                        .addComponent(btLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btBorrar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 700, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        try {
            jtNombre.setText("");
            jtDesc.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
            jrbEstado.setSelected(false);
            if (!jtId.getText().isEmpty()) {
                if ((Integer.parseInt(jtId.getText())) > 0) {
                    Producto prod = new Producto();
                    prod = pd.obtenerProductoPorid(Integer.parseInt(jtId.getText()));
                    jtNombre.setText(prod.getNombreProducto());
                    jtDesc.setText(prod.getDescripcion());
                    jtPrecio.setText(prod.getPrecioActual() + "");
                    jtStock.setText(prod.getStock() + "");
                    if (prod.isEstado()) {
                        jrbEstado.setSelected(true);
                    } else {
                        jrbEstado.setSelected(false);
                    }
                    if (jtNombre.getText().isEmpty()) {
                        jtNombre.setText("");
                        jtDesc.setText("");
                        jtPrecio.setText("");
                        jtStock.setText("");
                        jrbEstado.setSelected(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El codigo debe ser mayor a 0(cero)", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    jtId.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debes ingresar un codigo", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El codigo debe ser en formato numerico", "ERROR", JOptionPane.ERROR_MESSAGE);
            jtId.setText("");
        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        // TODO add your handling code here:
        try {
            if (!jtId.getText().isEmpty()) {
                if ((Integer.parseInt(jtId.getText())) > 0) {
                    if (jtNombre.getText().isEmpty()) {
                        btBuscarActionPerformed(evt);
                    }
                    if (!jtNombre.getText().isEmpty()) {
                        int x = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas dar de baja el producto?",
                                "ADVERTENCIA", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
                        if (x == 0) {
                            pd.borrarProducto(Integer.parseInt(jtId.getText()));
                            jrbEstado.setSelected(false);
                        }
                        limpiarCampos();
                        listarProductos();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El codigo debe ser mayor a 0(cero)", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    jtId.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debes ingresar un codigo", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El codigo debe ser en formato numerico", "ERROR", JOptionPane.ERROR_MESSAGE);
            jtId.setText("");
        }
    }//GEN-LAST:event_btBorrarActionPerformed

    private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarActionPerformed
        // TODO add your handling code here:
        try {
            if (!jtId.getText().isEmpty() && !jtNombre.getText().isEmpty() && !jtDesc.getText().isEmpty()
                    && !jtPrecio.getText().isEmpty() && !jtStock.getText().isEmpty()) {
                if ((Integer.parseInt(jtId.getText())) > 0) {
                    int i = Integer.parseInt(jtId.getText());
                    String n = jtNombre.getText();
                    String d = jtDesc.getText();
                    double p = Double.parseDouble(jtPrecio.getText());
                    int s = Integer.parseInt(jtStock.getText());
                    if (!jrbEstado.isSelected()) {
                        int x = JOptionPane.showConfirmDialog(this, "El estado esta desactivado ¿Deseas activarlo?", "",
                                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (x == 0) {
                            jrbEstado.setSelected(true);
                        }
                    }
                    boolean e = jrbEstado.isSelected();
                    Producto prod = new Producto(i, n, d, p, s, e);
                    if (pd.obtenerProducto(i) == null) {
                        pd.guardarProducto(prod);
                    } else {
                        int x = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres modificar el producto?", "",
                                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (x == 0) {
                            pd.modificarProducto(prod);
                        }
                    }
                    limpiarCampos();
                    listarProductos();
                } else {
                    JOptionPane.showMessageDialog(this, "El codigo debe ser mayor a 0(cero)", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    jtId.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Quedan campos sin llenar", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Los campos codigo, precio y stock deben ser numericos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAgregarActionPerformed

    private void jtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdKeyTyped
        // validar numeros en textfield
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jtIdKeyTyped

    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyTyped
        // Validar letras en textfield
        /*char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z')){
            evt.consume();
        }*/
    }//GEN-LAST:event_jtNombreKeyTyped

    private void jtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDescKeyTyped
        // TODO add your handling code here:
        /*char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z')){
            evt.consume();
        }*/
    }//GEN-LAST:event_jtDescKeyTyped

    private void jtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '.' || c > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtPrecioKeyTyped

    private void jtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtStockKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jtStockKeyTyped

    private void jtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyReleased
        // TODO add your handling code here:
        if (!jtNombre.getText().isEmpty()) {
            jtable.clearSelection();
            listarProductos();
        }
    }//GEN-LAST:event_jtNombreKeyReleased

    private void jtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdKeyReleased
        // TODO add your handling code here:
        if (!jtId.getText().isEmpty()) {
            jtable.clearSelection();
            listarProductos();
        }
    }//GEN-LAST:event_jtIdKeyReleased

    private void jtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdKeyPressed

    private void jtDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDescKeyReleased
        // TODO add your handling code here:
        if (!jtDesc.getText().isEmpty()) {
            jtable.clearSelection();
            listarProductos();
        }
    }//GEN-LAST:event_jtDescKeyReleased

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        if (jtable.getSelectedRow() != -1) {
            int fila = jtable.getSelectedRow();
            jtId.setText(jtable.getValueAt(fila, 0) + "");
            jtNombre.setText(jtable.getValueAt(fila, 1) + "");
            jtDesc.setText(jtable.getValueAt(fila, 2) + "");
            jtPrecio.setText(jtable.getValueAt(fila, 3) + "");
            jtStock.setText(jtable.getValueAt(fila, 4) + "");
            if ((jtable.getValueAt(fila, 5) + "").equalsIgnoreCase("true")) {
                jrbEstado.setSelected(true);
            } else {
                jrbEstado.setSelected(false);
            }
            //listarProductos();
        }
    }//GEN-LAST:event_jtableMouseClicked

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        jtId.setText("");
        jtNombre.setText("");
        jtDesc.setText("");
        jtPrecio.setText("");
        jtStock.setText("");
        jrbEstado.setSelected(false);
        jtable.clearSelection();
        listarProductos();
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void jlSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseClicked

        Principal mainFrame = (Principal) SwingUtilities.getWindowAncestor(this);
        if (mainFrame != null) {
            // Llama al método en MainFrame
            mainFrame.mostrarMenu();
        }

        this.dispose();
    }//GEN-LAST:event_jlSalirMouseClicked

    private void jlSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseEntered

        jpSalir.setBackground(new Color(204, 0, 0));
        jlSalir.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_jlSalirMouseEntered

    private void jlSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMouseExited

        jpSalir.setBackground(new Color(0, 51, 153));
        jlSalir.setForeground(Color.white);
    }//GEN-LAST:event_jlSalirMouseExited

    private void jlSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSalirMousePressed
        jpSalir.setBackground(new Color(255, 51, 51));
        jlSalir.setForeground(Color.black);
    }//GEN-LAST:event_jlSalirMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlSalir;
    private javax.swing.JPanel jpSalir;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtDesc;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStock;
    private javax.swing.JTable jtable;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables

    private void setearIcono(JLabel jLabelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(120, 120, Image.SCALE_DEFAULT));
        jLabelName.setIcon(icon);
        this.repaint();
    }

    private void limpiarCampos() {
        jtId.setText("");
        jtNombre.setText("");
        jtDesc.setText("");
        jtPrecio.setText("");
        jtStock.setText("");
        jrbEstado.setSelected(false);
    }

    public void listarProductos() {

        //tabla.setRowCount(0);
        ProductoData pd = new ProductoData();

//        ArrayList<Producto> array = new ArrayList<>(); 
//        array = pd.listarProductoPorId(Integer.parseInt(jtId.getText()));
        if (jtable.getSelectedRow() == -1) {
            if (!jtId.getText().equalsIgnoreCase("") || !jtNombre.getText().isEmpty() || !jtDesc.getText().isEmpty()) {
                tabla.setRowCount(0);
                for (Producto a : pd.listarProductoPorNombreDescYId(jtId.getText(), jtNombre.getText(), jtDesc.getText())) {
                    tabla.addRow(new Object[]{a.getIdProducto(), a.getNombreProducto(), a.getDescripcion(),
                        a.getPrecioActual(), a.getStock(), a.isEstado()});
                }
            } else {
                tabla.setRowCount(0);
                for (Producto a : pd.listarProducto()) {
                    tabla.addRow(new Object[]{a.getIdProducto(), a.getNombreProducto(), a.getDescripcion(),
                        a.getPrecioActual(), a.getStock(), a.isEstado()});
                }
            }
        }
    }

    public void borrado() {
        jtId.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                listarProductos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }

        });

        jtNombre.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                listarProductos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }

        });

        jtDesc.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                listarProductos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }

        });
    }
}
